### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by pathumego** [mooniak/ayanna-font#43]
@paarandika 

BTW I think we should try to figure out a way to intergrated Welipilla base scripts as a git module into a repo. That way we can do any updates to scripts centrally.
```
Traceback (most recent call last):
  File "build.py", line 59, in <module>
    builder.build()
  File "/usr/local/lib/python2.7/dist-packages/hindkit-0.2.1-py2.7.egg/hindkit/builder.py", line 200, in build
    output_path = 'features/GENERATED_classes.fea'
  File "/usr/local/lib/python2.7/dist-packages/hindkit-0.2.1-py2.7.egg/hindkit/builder.py", line 424, in generate_glyph_classes
    glyph_names = [glyph.name for glyph in filter(filter_function, font)]
  File "/usr/local/lib/python2.7/dist-packages/robofab/objects/objectsBase.py", line 180, in __iter__
    yield self[name]
  File "/usr/local/lib/python2.7/dist-packages/robofab/objects/objectsBase.py", line 184, in __getitem__
    return self.layers.getDefaultLayer()[glyphName]
AttributeError: 'RFont' object has no attribute 'layers'
```

**Comment by paarandika** [comment]
Should work now
